import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal Notice — Global Tariff Hub",
  description: "Legal notice, limitation of liability and intellectual property rights for Global Tariff Hub.",
};

export default function Legal() {
  return (
    <div style={{ backgroundColor: "#0A0A0F", minHeight: "100vh", color: "#FFFFFF", fontFamily: "'Helvetica Neue', Arial, sans-serif" }}>

      {/* Navbar */}
      <nav style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 40px", borderBottom: "1px solid rgba(255,255,255,0.08)" }}>
        <Link href="/en" style={{ display: "flex", alignItems: "center", gap: 10, textDecoration: "none", color: "#FFFFFF" }}>
          <div style={{ width: 34, height: 34, borderRadius: 7, background: "linear-gradient(135deg, #0057FF, #0D1B3E)", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 800, fontSize: 11, color: "#C9A84C", border: "1px solid rgba(201,168,76,0.5)" }}>GTH</div>
          <span style={{ fontWeight: 700, fontSize: 16 }}>Global Tariff Hub</span>
        </Link>
        <div style={{ display: "flex", gap: 24 }}>
          <Link href="/legales" style={{ color: "rgba(255,255,255,0.5)", fontSize: 13, textDecoration: "none" }}>Ver en español</Link>
          <Link href="/terms" style={{ color: "rgba(255,255,255,0.5)", fontSize: 13, textDecoration: "none" }}>Terms of Use</Link>
          <Link href="/privacy" style={{ color: "rgba(255,255,255,0.5)", fontSize: 13, textDecoration: "none" }}>Privacy Policy</Link>
        </div>
      </nav>

      <main style={{ maxWidth: 760, margin: "0 auto", padding: "60px 40px 80px" }}>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <span style={{ background: "rgba(201,168,76,0.15)", border: "1px solid rgba(201,168,76,0.4)", borderRadius: 20, padding: "5px 16px", color: "#C9A84C", fontSize: 12, fontWeight: 600 }}>Legal</span>
          <h1 style={{ fontSize: 34, fontWeight: 800, marginTop: 20, marginBottom: 8, letterSpacing: -0.5 }}>Legal Notice</h1>
          <p style={{ color: "rgba(255,255,255,0.35)", fontSize: 13 }}>Last updated: June 2026</p>
        </div>

        {/* Primary notice */}
        <div style={{ background: "linear-gradient(135deg, rgba(239,68,68,0.08), rgba(239,68,68,0.04))", border: "1px solid rgba(239,68,68,0.25)", borderRadius: 14, padding: "28px 32px", marginBottom: 20 }}>
          <p style={{ fontSize: 13, fontWeight: 800, color: "#ef4444", marginBottom: 12, textTransform: "uppercase", letterSpacing: 1 }}>⚠ Important notice</p>
          <p style={{ fontSize: 16, color: "rgba(255,255,255,0.85)", lineHeight: 1.8, fontWeight: 500 }}>
            <strong style={{ color: "#FFF" }}>Global Tariff Hub</strong> provides <strong style={{ color: "#FFF" }}>analytical support tools</strong> for international trade. Definitive tariff classification, the application of trade agreements, and applicable regulatory requirements must always be verified by <strong style={{ color: "#C9A84C" }}>qualified professionals</strong> and/or the relevant customs authorities.
          </p>
        </div>

        {/* AI notice */}
        <div style={{ background: "rgba(168,85,247,0.06)", border: "1px solid rgba(168,85,247,0.25)", borderRadius: 14, padding: "20px 28px", marginBottom: 40 }}>
          <p style={{ fontSize: 13, fontWeight: 800, color: "rgba(168,85,247,0.9)", marginBottom: 8, textTransform: "uppercase", letterSpacing: 1 }}>🤖 AI Notice</p>
          <p style={{ fontSize: 14, color: "rgba(255,255,255,0.7)", lineHeight: 1.75 }}>
            Results generated by <strong style={{ color: "#FFF" }}>artificial intelligence</strong> are <strong style={{ color: "#FFF" }}>indicative only</strong> and do not constitute legal, tax, or customs advice. Users must verify any tariff classification with a licensed professional before using it in official documentation.
          </p>
        </div>

        {/* Sections */}
        {[
          {
            icon: "📋",
            title: "Nature of the service",
            body: "Global Tariff Hub is an analytical support tool for international trade. It allows users to estimate tariffs, simulate transactions, and calculate import costs. All results are indicative estimates and do not constitute a definitive customs assessment, nor do they represent legal or customs advice.",
          },
          {
            icon: "🏛",
            title: "Professional consultation required",
            body: "Before carrying out any import or export transaction, users must consult a licensed customs broker, a legal advisor specializing in international trade, and/or an accountant with experience in cross-border operations. GTH assumes no liability for commercial decisions made solely on the basis of data provided by the platform.",
          },
          {
            icon: "🌐",
            title: "Reference sources",
            body: "GTH draws on data from the following public sources: WTO API (World Trade Organization), BrasilAPI / Siscomex (Brazilian Receita Federal), and TARIC (European Commission). These sources are subject to regulatory changes that may not be immediately reflected on the platform. GTH acts as a research intermediary and does not redistribute complete databases or guarantee that data is current at the exact moment of any given query.",
          },
          {
            icon: "🤖",
            title: "Use of artificial intelligence",
            body: "Image- and description-based tariff classification uses AI models (Anthropic Claude). Results are indicative and do not constitute legal, tax, or customs advice. Automated classification may contain errors. Users must always verify the tariff code with a licensed professional before using it in official documentation or making commercial decisions based on it.",
          },
          {
            icon: "⚖️",
            title: "Limitation of liability",
            body: "Global Tariff Hub shall not be liable for: tariff classification errors; discrepancies between estimated and officially assessed rates; customs penalties or fines; economic losses arising from use of the platform; or outdated regulatory data. Use of GTH is entirely at the user's own risk.",
          },
          {
            icon: "🔄",
            title: "Data updates",
            body: "MFN tariff rates are sourced from the WTO API. TARIC data is synchronized monthly. NCM nomenclature is retrieved in real time from BrasilAPI. Despite these efforts, international trade regulations change frequently. GTH does not guarantee that data is current at the exact moment of any query.",
          },
        ].map((section, i) => (
          <div key={i} style={{ display: "flex", gap: 20, marginBottom: 32, paddingBottom: 32, borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
            <span style={{ fontSize: 24, marginTop: 2, flexShrink: 0 }}>{section.icon}</span>
            <div>
              <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 10, color: "#FFFFFF" }}>{section.title}</h2>
              <p style={{ color: "rgba(255,255,255,0.55)", lineHeight: 1.85, fontSize: 14 }}>{section.body}</p>
            </div>
          </div>
        ))}

        {/* Copyright */}
        <div style={{ background: "rgba(13,27,62,0.6)", border: "1px solid rgba(0,87,255,0.2)", borderRadius: 14, padding: "28px 32px", marginTop: 8 }}>
          <p style={{ fontSize: 13, fontWeight: 800, color: "rgba(255,255,255,0.7)", marginBottom: 16, textTransform: "uppercase", letterSpacing: 1 }}>© Intellectual Property</p>

          <p style={{ fontSize: 14, color: "rgba(255,255,255,0.6)", lineHeight: 1.85, marginBottom: 16 }}>
            <strong style={{ color: "#FFF" }}>© 2026 Global Tariff Hub.</strong> All rights reserved.
          </p>

          <p style={{ fontSize: 14, color: "rgba(255,255,255,0.6)", lineHeight: 1.85, marginBottom: 16 }}>
            The design, source code, brand, texts, structure, and original content of this platform are the property of <strong style={{ color: "#FFF" }}>Global Tariff Hub</strong> and are protected under the intellectual property laws of the Oriental Republic of Uruguay and applicable international treaties, including the <strong style={{ color: "rgba(255,255,255,0.8)" }}>Berne Convention</strong> for the Protection of Literary and Artistic Works and the WTO <strong style={{ color: "rgba(255,255,255,0.8)" }}>TRIPS Agreement</strong>.
          </p>

          <p style={{ fontSize: 14, color: "rgba(255,255,255,0.6)", lineHeight: 1.85, marginBottom: 16 }}>
            The platform was originally created and developed in <strong style={{ color: "rgba(255,255,255,0.8)" }}>June 2025</strong>. Any reproduction, distribution, transformation, or public communication of GTH's proprietary content — in whole or in part — without the express written authorization of the rights holder is strictly prohibited.
          </p>

          <p style={{ fontSize: 14, color: "rgba(255,255,255,0.6)", lineHeight: 1.85 }}>
            Tariff data is sourced from public reference databases (WTO, Siscomex, TARIC EU) and cited with appropriate attribution. GTH claims no rights over such data and does not guarantee its accuracy or currency at the time of any query.
          </p>
        </div>

        {/* Contact */}
        <div style={{ marginTop: 32, padding: "20px 28px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12 }}>
          <p style={{ fontSize: 13, color: "rgba(255,255,255,0.5)", lineHeight: 1.7 }}>
            Legal enquiries: <a href="mailto:analia@globaltariffhub.com" style={{ color: "#0057FF", textDecoration: "none", fontWeight: 600 }}>analia@globaltariffhub.com</a>
          </p>
        </div>

        <div style={{ marginTop: 32, textAlign: "center" }}>
          <Link href="/en" style={{ color: "rgba(255,255,255,0.3)", fontSize: 13, textDecoration: "none" }}>← Back to home</Link>
        </div>
      </main>

      <footer style={{ borderTop: "1px solid rgba(255,255,255,0.06)", padding: "24px 40px", textAlign: "center" }}>
        <div style={{ display: "flex", justifyContent: "center", gap: 24, marginBottom: 12, flexWrap: "wrap" }}>
          <Link href="/terms" style={{ fontSize: 12, color: "rgba(255,255,255,0.25)", textDecoration: "none" }}>Terms of Use</Link>
          <Link href="/privacy" style={{ fontSize: 12, color: "rgba(255,255,255,0.25)", textDecoration: "none" }}>Privacy Policy</Link>
          <Link href="/legal" style={{ fontSize: 12, color: "rgba(255,255,255,0.25)", textDecoration: "none" }}>Legal Notice</Link>
        </div>
        <p style={{ fontSize: 11, color: "rgba(255,255,255,0.15)" }}>© 2026 Global Tariff Hub. All rights reserved.</p>
      </footer>
    </div>
  );
}
